/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Jacob
 * Oct 5, 2018
 * Creates new form to allow the selection and purchase of ice cream scoops
 */

import java.text.*;
//import java.awt.Color;

public class Making_Purchases extends javax.swing.JFrame {
        
    /**
     *
     */
    public Making_Purchases() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        vanillaSelectTextField = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        instructionsScrollPane = new javax.swing.JScrollPane();
        instructionsTextArea = new javax.swing.JTextArea();
        icecreamPhotoLabel = new javax.swing.JLabel();
        vanillaTitleLabel = new javax.swing.JLabel();
        strawberryTextField = new javax.swing.JTextField();
        strawberryTitleLabel = new javax.swing.JLabel();
        vanillaTextField = new javax.swing.JTextField();
        chocolatTitleLabel = new javax.swing.JLabel();
        chocolatTextField = new javax.swing.JTextField();
        orderButton = new javax.swing.JButton();
        grandtotalTitleLabel = new javax.swing.JLabel();
        taxesTitleLabel = new javax.swing.JLabel();
        subtotalTitleLabel = new javax.swing.JLabel();
        subtotalOutputLabel = new javax.swing.JTextField();
        grandtotalOutputLabel = new javax.swing.JTextField();
        taxesOutputLabel = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vanillaSelectTextField.setBackground(new java.awt.Color(255, 204, 204));
        vanillaSelectTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        titleLabel.setFont(new java.awt.Font("Old English Text MT", 0, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(153, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText(" Papa's Ice-Creamery ");

        instructionsTextArea.setEditable(false);
        instructionsTextArea.setBackground(new java.awt.Color(255, 206, 206));
        instructionsTextArea.setColumns(20);
        instructionsTextArea.setFont(new java.awt.Font("OCR-A BT", 0, 13)); // NOI18N
        instructionsTextArea.setRows(2);
        instructionsTextArea.setText("Please select how many scoops of each flavour of ice cream you\nwould like. Then kindly click \"order\" to recieve your total.");
        instructionsTextArea.setAutoscrolls(false);
        instructionsTextArea.setBorder(null);
        instructionsScrollPane.setViewportView(instructionsTextArea);

        icecreamPhotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/660b9f099fff3269ede645377bc511bf-ice-cream-cartoon-by-vexels (1).png"))); // NOI18N

        vanillaTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vanillaTitleLabel.setText("One Vanilla Scoop ($2.99CAN):");

        strawberryTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        strawberryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryTextFieldActionPerformed(evt);
            }
        });

        strawberryTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        strawberryTitleLabel.setText("One Strawberry Scoop ($3.99CAN):");

        vanillaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vanillaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanillaTextFieldActionPerformed(evt);
            }
        });

        chocolatTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chocolatTitleLabel.setText("One Chocolate Scoop ($3.99CAN):");

        chocolatTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chocolatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolatTextFieldActionPerformed(evt);
            }
        });

        orderButton.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        orderButton.setText("ORDER");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        grandtotalTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        grandtotalTitleLabel.setText("Grand Total: ($)");

        taxesTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        taxesTitleLabel.setText("Taxes (13%): ($)");

        subtotalTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        subtotalTitleLabel.setText("Subtotal: ($)");

        subtotalOutputLabel.setEditable(false);

        grandtotalOutputLabel.setEditable(false);

        taxesOutputLabel.setEditable(false);

        javax.swing.GroupLayout vanillaSelectTextFieldLayout = new javax.swing.GroupLayout(vanillaSelectTextField);
        vanillaSelectTextField.setLayout(vanillaSelectTextFieldLayout);
        vanillaSelectTextFieldLayout.setHorizontalGroup(
            vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vanillaSelectTextFieldLayout.createSequentialGroup()
                .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(vanillaSelectTextFieldLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instructionsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(icecreamPhotoLabel)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vanillaSelectTextFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vanillaSelectTextFieldLayout.createSequentialGroup()
                        .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vanillaTitleLabel)
                            .addComponent(chocolatTitleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chocolatTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vanillaTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vanillaSelectTextFieldLayout.createSequentialGroup()
                        .addComponent(strawberryTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(strawberryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vanillaSelectTextFieldLayout.createSequentialGroup()
                        .addComponent(taxesTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taxesOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vanillaSelectTextFieldLayout.createSequentialGroup()
                        .addComponent(subtotalTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subtotalOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vanillaSelectTextFieldLayout.createSequentialGroup()
                        .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(vanillaSelectTextFieldLayout.createSequentialGroup()
                        .addComponent(grandtotalTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grandtotalOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        vanillaSelectTextFieldLayout.setVerticalGroup(
            vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vanillaSelectTextFieldLayout.createSequentialGroup()
                .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vanillaSelectTextFieldLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instructionsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vanillaSelectTextFieldLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icecreamPhotoLabel)))
                .addGap(36, 36, 36)
                .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vanillaTitleLabel)
                    .addComponent(vanillaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxesTitleLabel)
                    .addComponent(taxesOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotalTitleLabel)
                    .addComponent(subtotalOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chocolatTitleLabel)
                    .addComponent(chocolatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grandtotalTitleLabel)
                    .addComponent(grandtotalOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(vanillaSelectTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strawberryTitleLabel)
                    .addComponent(strawberryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vanillaSelectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vanillaSelectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void strawberryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strawberryTextFieldActionPerformed

    private void vanillaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanillaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vanillaTextFieldActionPerformed

    private void chocolatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chocolatTextFieldActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        //declare decimal format
        DecimalFormat money = new DecimalFormat ("####.00");
        
        //set up variables
        double vanillaRequested = Double.parseDouble(vanillaTextField.getText());
        double chocRequested = Double.parseDouble(chocolatTextField.getText());
        double strawRequested = Double.parseDouble(strawberryTextField.getText());
        final double VANILLA_PRICE_ONE = 2.99;//$
        final double CHOC_PRICE_ONE = 3.99;//$
        final double STRAW_PRICE_ONE = 3.99;//$
        final double HST_TAX = 0.13;//13%
        double taxesTotal = 0.00;//$
        double subTotal = 0.00;//$
        double grandTotal = 0.00;//$
        
        //algorithms
        subTotal = ((vanillaRequested*VANILLA_PRICE_ONE)+(chocRequested*CHOC_PRICE_ONE)+(strawRequested*STRAW_PRICE_ONE));
        taxesTotal = subTotal*HST_TAX;
        grandTotal = subTotal+taxesTotal;
        
        //output to slots
        subtotalOutputLabel.setText(""+money.format(subTotal));
        taxesOutputLabel.setText(""+money.format(taxesTotal));
        grandtotalOutputLabel.setText(""+money.format(taxesTotal));
    }//GEN-LAST:event_orderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Making_Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Making_Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Making_Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Making_Purchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Making_Purchases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chocolatTextField;
    private javax.swing.JLabel chocolatTitleLabel;
    private javax.swing.JTextField grandtotalOutputLabel;
    private javax.swing.JLabel grandtotalTitleLabel;
    private javax.swing.JLabel icecreamPhotoLabel;
    private javax.swing.JScrollPane instructionsScrollPane;
    private javax.swing.JTextArea instructionsTextArea;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JButton orderButton;
    private javax.swing.JTextField strawberryTextField;
    private javax.swing.JLabel strawberryTitleLabel;
    private javax.swing.JTextField subtotalOutputLabel;
    private javax.swing.JLabel subtotalTitleLabel;
    private javax.swing.JTextField taxesOutputLabel;
    private javax.swing.JLabel taxesTitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel vanillaSelectTextField;
    private javax.swing.JTextField vanillaTextField;
    private javax.swing.JLabel vanillaTitleLabel;
    // End of variables declaration//GEN-END:variables
}
